[build]
command = "cargo run -- -c src/index.json -t src/index.html"
publish = "dist"

[build.processing]
skip_processing = true

[[redirects]]
from = "https://nifty-dubinsky-1f8fdd.netlify.app/*"
to = "https://resume.troyv.dev/:splat"
status = 301
force = true

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
